server:
    port: 8102
    NODE_ENV: development

database:
    url: mongodb://root:root@localhost:27017/billing-db?authSource=admin&w=1

auth:
    jwksUri: http://localhost:8100/.well-known/jwks.json
